import type { Metadata } from 'next';
import Footer from './_components/footer/Footer';
import Header from './_components/header/Header';
import { roboto } from './fonts';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={roboto.className}>
        <Header />
        <main className='bg-white'>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
